use 5.020;
use strict;
use warnings;
use ExtUtils::MakeMaker;
use Config;
use Getopt::Long 'GetOptions';
use File::Path 'mkpath', 'rmtree';

GetOptions(
  # Compiler and linker flags
  'cc=s' => \my $cc,
  'ccflag=s' => \my @ccflags,
  'define=s' => \my @defines,
  'include-dir=s' => \my @include_dirs,
  'ld=s' => \my $ld,
  'ldflag=s' => \my @ldflags,
  'lib=s' => \my @libs,
  'lib-dir=s' => \my @lib_dirs,
  'debug' => \my $debug,
  'build-type=s' => \my $build_type,
  'asan-on-linux' => \my $asan_on_linux,
  'msvc' => \my $msvc,
  
  # Build target settings
  'no-build-spvm-modules' => \my $no_build_spvm_modules,
  
  # For cpan/cpanm to run Makefile.PL
  'meta' => \my $meta,
  
  # Parallel settings
  'parallel-make' => \my $paralle_make,
  'parallel-test' => \my $paralle_test,
  'jobs=i' => \my $jobs,
) or die 'Invalid command line options are specified.';

if ($meta) {
  $no_build_spvm_modules = 1;
}

my $build_dir = '.spvm_build';
mkpath $build_dir;

my $config_global_file = '.spvm_build/global.build';
&generate_config_global_file($config_global_file, {
  cc            => $cc,
  ccflags       => \@ccflags,
  defines       => \@defines,
  include_dirs  => \@include_dirs,
  ld            => $ld,
  ldflags       => \@ldflags,
  libs          => \@libs,
  lib_dirs      => \@lib_dirs,
  debug         => $debug,
  build_type    => $build_type,
  asan_on_linux => $asan_on_linux,
  msvc          => $msvc,
});

my $asan_logs_dir = ".spvm_build/asan_logs";
if ($asan_on_linux) {
  rmtree $asan_logs_dir;
  mkpath $asan_logs_dir;
}

unless ($meta) {
  require SPVM::Builder::Util::API;
}

my $gnu_make;
unless ($meta) {
  $gnu_make = SPVM::Builder::Util::API::search_gnu_make_command();
}

unless ($meta) {
  # Jobs count for parallel build and tests
  unless (defined $jobs) {
    my $cpus = SPVM::Builder::Util::API::get_cpu_count();
    $jobs = $cpus + 2;
  }
  # Limit the maximum number of parallel jobs to 16
  if ($jobs > 16) {
    $jobs = 16;
  }
}

# Check supported environment
unless ($meta) {
  unless ($gnu_make) {
    warn "Building SPVM modules needs GNU Make.\n";
    die "OS unsupported\n";
  }
}

# Always true in SPVM modern build
$paralle_make = 1;
$paralle_test = 1;

my %configure_and_runtime_requires = ('SPVM' => '0.990195');
my @test_clean_files = map { "t/" . join('', map { '*/' } 1 .. $_) . "*.$Config{dlext}" } (1 .. 10);

WriteMakefile(
  NAME              => 'SPVM::Resource::Zlib',
  VERSION_FROM      => 'lib/SPVM/Resource/Zlib.pm',
  LICENSE           => 'mit',
  ($] >= 5.005 ?    
    (ABSTRACT_FROM  => 'lib/SPVM/Resource/Zlib.pm',
     AUTHOR         => 'Yuki Kimoto<kimoto.yuki@gmail.com>') : ()),
  test => {TESTS => 't/*.t t/*/*.t t/*/*/*.t t/*/*/*/*.t'},
  clean => {FILES => ".spvm_build @test_clean_files"},
  META_MERGE => {
    'meta-spec' => { version => 2 },
    resources => {
      repository => {
        type => 'git',
        url  => 'https://github.com/yuki-kimoto/SPVM-Resource-Zlib.git',
        web  => 'https://github.com/yuki-kimoto/SPVM-Resource-Zlib',
      },
      bugtracker => {
        web  => "https://github.com/yuki-kimoto/SPVM-Resource-Zlib/issues",
      },
    },
  },
  MAKE => $gnu_make,
  macro => {
    $paralle_make ? (MAKEFLAGS => "-j$jobs") : (),
    $paralle_test ? ('override TEST_VERBOSE' => "scalar (eval chr(36) . q(ENV{HARNESS_OPTIONS}='j$jobs'), 0)") : (),
    $asan_on_linux ? ('override FULLPERL' => qq|LD_PRELOAD=\$\$($Config{cc} -print-file-name=libasan.so) ASAN_OPTIONS="log_path=$asan_logs_dir/asan.log:exitcode=0" $^X|) : (),
  },
  NORECURS => 1,
  CONFIGURE_REQUIRES => {
    %configure_and_runtime_requires,
  },
  PREREQ_PM         => {
    %configure_and_runtime_requires,
  },
  TEST_REQUIRES => {
    'Test::More' => '0.92',
  },
);

package MY {
  sub postamble {
    my $make_rule = '';
    
    unless ($no_build_spvm_modules) {
      require SPVM::Builder::Util::API;
      
      my $options = {};
      $options->{config_global_file} = $config_global_file;
      $options->{order_only_dependent_files} = ['pm_to_blib'];
      
      my $test_class_search_dir = 't/lib';
      $make_rule .= SPVM::Builder::Util::API::create_make_rule_native('TestCase::Zlib', {%$options, output_dir => $test_class_search_dir, class_search_dir => [$test_class_search_dir]});
    }
    
    return $make_rule;
  }
}

sub generate_config_global_file {
  my ($config_global_file, $options) = @_;
  
  my $cc            = $options->{cc};
  my $ccflags       = $options->{ccflags} // [];
  my $defines       = $options->{defines} // [];
  my $include_dirs  = $options->{include_dirs};
  my $ld            = $options->{ld};
  my $ldflags       = $options->{ldflags} // [];
  my $libs          = $options->{libs};
  my $lib_dirs      = $options->{lib_dirs};
  my $debug         = $options->{debug};
  my $build_type    = $options->{build_type};
  my $asan_on_linux = $options->{asan_on_linux};
  my $msvc          = $options->{msvc};
  
  if ($debug) {
    $build_type = 'Debug';
  }
  
  if ($asan_on_linux) {
    push @$ccflags, "-fsanitize=address", "-fno-omit-frame-pointer";
    push @$ldflags, "-fsanitize=address";
  }
  
  my $config_global_content = '';
  
  $config_global_content .= <<"EOS";
my \$config_global = SPVM::Builder::Config::Global->new;
EOS
  
  if ($msvc) {
    $config_global_content .= <<"EOS";
use SPVM::Builder::Config::Global::MSVC;
\$config_global = SPVM::Builder::Config::Global::MSVC->new;
EOS
  }
  
  if (defined $build_type) {
    $config_global_content .= <<"EOS";
\$config_global->build_type('$build_type');
EOS
  }
  
  if (defined $cc) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'cc' => '$cc'});
EOS
  }
  
  for my $ccflag (@$ccflags) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'+ccflags' => ['$ccflag']});
EOS
  }
  
  for my $define (@$defines) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'+defines' => ['$define']});
EOS
  }
  
  for my $include_dir (@$include_dirs) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'+include_dirs' => ['$include_dir']});
EOS
  }
  
  if (defined $ld) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'ld' => '$ld'});
EOS
  }
  
  for my $ldflag (@$ldflags) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'+ldflags' => ['$ldflag']});
EOS
  }
  
  for my $lib (@$libs) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'+libs' => ['$lib']});
EOS
  }
  
  for my $lib_dir (@$lib_dirs) {
    $config_global_content .= <<"EOS";
\$config_global->build_rule_any({'+lib_dirs' => ['$lib_dir']});
EOS
  }
  
  $config_global_content .= <<"EOS";
\$config_global;
EOS
  
  open my $fh, '>', $config_global_file or die "Can't open file '$config_global_file': $!";
  print $fh $config_global_content;
}

1;
